# TCL File Generated by Component Editor 18.1
# Tue May 14 03:04:23 EDT 2019
# DO NOT MODIFY


# 
# fpga "fpga" v1.0
#  2019.05.14.03:04:23
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module fpga
# 
set_module_property DESCRIPTION ""
set_module_property NAME fpga
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME fpga
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fpga_top_level
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fpga_top_level.sv SYSTEM_VERILOG PATH fpga_top_level.sv TOP_LEVEL_FILE
add_fileset_file fifo_buffer.sv SYSTEM_VERILOG PATH fifo_buffer.sv
add_fileset_file memory.sv SYSTEM_VERILOG PATH memory.sv
add_fileset_file vga_display.sv SYSTEM_VERILOG PATH vga_display.sv
add_fileset_file common.sv SYSTEM_VERILOG PATH common.sv CONTAINS_INLINE_CONFIGURATION
add_fileset_file vga_counters.sv SYSTEM_VERILOG PATH vga_counters.sv


# 
# parameters
# 


# 
# module assignments
# 
set_module_assignment embeddedsw.dts.group fpga
set_module_assignment embeddedsw.dts.name fpga
set_module_assignment embeddedsw.dts.vendor csee4840


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock50
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point hps
# 
add_interface hps avalon end
set_interface_property hps addressUnits WORDS
set_interface_property hps associatedClock clock50
set_interface_property hps associatedReset reset
set_interface_property hps bitsPerSymbol 8
set_interface_property hps burstOnBurstBoundariesOnly false
set_interface_property hps burstcountUnits WORDS
set_interface_property hps explicitAddressSpan 0
set_interface_property hps holdTime 0
set_interface_property hps linewrapBursts false
set_interface_property hps maximumPendingReadTransactions 0
set_interface_property hps maximumPendingWriteTransactions 0
set_interface_property hps readLatency 0
set_interface_property hps readWaitTime 1
set_interface_property hps setupTime 0
set_interface_property hps timingUnits Cycles
set_interface_property hps writeWaitTime 0
set_interface_property hps ENABLED true
set_interface_property hps EXPORT_OF ""
set_interface_property hps PORT_NAME_MAP ""
set_interface_property hps CMSIS_SVD_VARIABLES ""
set_interface_property hps SVD_ADDRESS_GROUP ""

add_interface_port hps hps_writedata writedata Input 8
add_interface_port hps hps_write write Input 1
add_interface_port hps hps_chipselect chipselect Input 1
add_interface_port hps hps_address address Input 3
set_interface_assignment hps embeddedsw.configuration.isFlash 0
set_interface_assignment hps embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment hps embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment hps embeddedsw.configuration.isPrintableDevice 0


# 
# connection point vga
# 
add_interface vga conduit end
set_interface_property vga associatedClock clock50
set_interface_property vga associatedReset reset
set_interface_property vga ENABLED true
set_interface_property vga EXPORT_OF ""
set_interface_property vga PORT_NAME_MAP ""
set_interface_property vga CMSIS_SVD_VARIABLES ""
set_interface_property vga SVD_ADDRESS_GROUP ""

add_interface_port vga vga_clk clk Output 1
add_interface_port vga vga_r r Output 8
add_interface_port vga vga_g g Output 8
add_interface_port vga vga_b b Output 8
add_interface_port vga vga_hs hs Output 1
add_interface_port vga vga_vs vs Output 1
add_interface_port vga vga_blank_n blank_n Output 1
add_interface_port vga vga_sync_n sync_n Output 1


# 
# connection point clock50
# 
add_interface clock50 clock end
set_interface_property clock50 clockRate 0
set_interface_property clock50 ENABLED true
set_interface_property clock50 EXPORT_OF ""
set_interface_property clock50 PORT_NAME_MAP ""
set_interface_property clock50 CMSIS_SVD_VARIABLES ""
set_interface_property clock50 SVD_ADDRESS_GROUP ""

add_interface_port clock50 clk50 clk Input 1

